// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PostValidationController from "./post_validation_controller"
application.register("post-validation", PostValidationController)

import UserAuthValidationController from "./user_auth_validation_controller"
application.register("user-auth-validation", UserAuthValidationController)
